#!/bin/bash

export CLASSPATH=postgresql-9.0-801.jdbc4.jar:.
javac evemapgraph/SolarSystem.java
javac evemapgraph/SolarSystemJump.java
javac evemapgraph/EveDB.java
javac evemapgraph/test_EveDB.java
java -Djdbc.drivers=org.postgresql.Driver evemapgraph.test_EveDB
